#include "stdio.h"
#include "time.h"
#include "stdlib.h"
#define MAX 16000

#define initial 1
#define visited 2
#define finished 3

int n,adj[MAX][MAX],state[MAX],flag=0,be=0;
int Graph()
{
    int i,max_edges,origin,destin;

    printf("\nEnter number of vertices and edges : ");
    scanf("%d %d",&n,&max_edges);
    for(i=1;i<=max_edges;i++)
    {
        printf("\nEnter %d edge: ",i);
        scanf("%d %d",&origin,&destin); 
        if( origin >= n || destin >= n || origin<0 || destin<0)
        {
            printf("\nInvalid edge!\n");
            i--;
        }
        else
        {
            adj[origin][destin] = initial;
        }
    }
    return 0;
}

int C_graph(){
    int max_edges,origin,destin;
//    srand(time(0));
//    n=rand()%MAX;
//    max_edges=rand()%n;
    n=1000;
    max_edges=16000;
    printf("No.of vertices = %d\nNo.of edges = %d\n",n,max_edges);
    int i;
    for(i=1;i<=max_edges;i++)
    {
        origin=rand()%n;
        destin=rand()%n;
        printf("Edge %lld: %d  %d\n",i,origin,destin);
        adj[origin][destin] = initial;
    }
    return 0;
}


int depth_first_search(int v)
{
    int i;
    state[v] = visited;
//    sleep(1);
    for(i=0; i<n; i++)
    {
        if(adj[v][i]==1)
        {
            if(state[i]==initial)
                depth_first_search(i);
            else if(state[i]==visited)
            {
                printf("\nBack edge  (%d,%d) found\n", v, i);
                be++;
                flag=1;
            }
        }
    }
    state[v] = finished;
    return 0;
}

int main()
{
    time_t start,end,process_start,process_end;
    printf("Enter 0 for random input generated by computer and 1 for manual input: ");
    int choice=0;
//    scanf("%d",&choice);
    time(&start);
    if (choice)
        Graph();
    else
        C_graph();
    time(&end);
    int i;
    process_start=clock();
    for(i=0; i< n; i++)
        state[i] = initial;
    depth_first_search(0);
    for(i=0; i < n; i++)
    {
        if(state[i] == initial)
            depth_first_search(i);
    }
    process_end=clock();
    if(flag)
        printf("\nGraph is cyclic\n");
    else
        printf("\nGraph is Acyclic\n");
    float time_taken,time_taken_process;
    time_taken=end-start;
    time_taken_process=process_end-process_start;
    printf("Time taken to construct graph: %f sec",time_taken);
    printf("\nTime taken for Depth first search: %f sec",time_taken_process);
    printf("\n%lf@\n$%lf",process_end,process_start);
    printf("\nBE:%d",be);
    return 0;
}
